version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
              - ./dist:/usr/share/nginx/html
              - ./nginx.conf:/etc/nginx/conf.d/default.conf
              - ./ssl/internal.databureau.set.crt:/etc/nginx/ssl/nginx.cert
              - ./ssl/internal.databureau.set.key:/etc/nginx/ssl/nginx.key
        restart: always
        networks:
              - code-network
networks:
      code-network:
          driver: bridge
